language: go

go:
    - 1.7.5
    - 1.8.5
    - 1.9.2
    - tip

before_install:
    - go get -u github.com/go-playground/overalls
    - go get -u github.com/mattn/goveralls
    - go get -u golang.org/x/tools/cmd/cover
    - go get -u github.com/golang/lint/golint
    - go get -u github.com/gordonklaus/ineffassign

before_script:
    - go vet ./...

script:
    - gofmt -d -s .
    - golint ./...
    - ineffassign ./
    - go test -v ./...
    - go test -race
